# Enhanced Tkinter GUI for Iris Recognition System with Sequential Display and Proportional Images
import tkinter as tk
from tkinter import filedialog, messagebox
from PIL import Image, ImageTk
import os
import time
import torch
import numpy as np
import pandas as pd
import cv2
from torchvision import transforms
from segmentation.seg_image import UNet, predict_single_image
from normalization.batch_normalization_half import normalize_iris_with_mask
from feature_extraction_encode.arcface_iris_model import ArcFaceIrisNet

# path to segmentation model unet_model.pth
SEG_MODEL_PATH = r"C:\Users\User\Desktop\unsw\y2\9773\code\iris_ml\segmentation_result\unet_model.pth"
# path to feature extraction model best_model.pt
ENCODE_MODEL_PATH = r"C:\Users\User\Desktop\unsw\y2\9773\code\iris_ml\feature_extraction_encoding_result\best_model.pt"
# path to saved encoding csv train_encodings.csv
ENCODE_DB_CSV = r"C:\Users\User\Desktop\unsw\y2\9773\code\iris_ml\feature_extraction_encoding_result\train_encodings.csv"
# path to threshold txt generated by train_arcface_v3 code
THRESHOLD_TXT = r"C:\Users\User\Desktop\unsw\y2\9773\code\iris_ml\feature_extraction_encoding_result\threshold.txt"
# path to predicted result
OUTPUT_DIR = r"system_predicted_outputs"
IMG_SIZE = (32, 512)
HASH_BITS = 256
NUM_CLASSES = 395
os.makedirs(OUTPUT_DIR, exist_ok=True)

def postprocess_mask(mask):

    kernel = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (5, 5))
    mask = cv2.morphologyEx(mask, cv2.MORPH_CLOSE, kernel)
    mask = cv2.morphologyEx(mask, cv2.MORPH_OPEN, kernel)

    num_labels, labels, stats, _ = cv2.connectedComponentsWithStats(mask, connectivity=8)
    if num_labels > 1:
        max_label = 1 + np.argmax(stats[1:, cv2.CC_STAT_AREA])  # 忽略背景
        mask = np.uint8(labels == max_label) * 255

    return mask
def segment_iris(image_path, model, device):
    model.eval()
    transform = transforms.Compose([
        transforms.Resize((256, 256)),
        transforms.ToTensor()
    ])
    image = Image.open(image_path).convert("RGB")
    orig_size = image.size
    input_tensor = transform(image).unsqueeze(0).to(device)
    with torch.no_grad():
        output = model(input_tensor)
    mask = output.squeeze().cpu().numpy()
    mask = (mask > 0.5).astype(np.uint8) * 255
    mask = cv2.resize(mask, orig_size, interpolation=cv2.INTER_NEAREST)
    mask = postprocess_mask(mask)
    return mask

def normalize_and_crop(image_path, mask):
    gray = cv2.imread(image_path, cv2.IMREAD_GRAYSCALE)
    norm = normalize_iris_with_mask(gray, mask)
    norm = norm[norm.shape[0] // 2:, :]
    return norm

def encode_feature(image, model, device):
    transform = transforms.Compose([
        transforms.Resize(IMG_SIZE),
        transforms.ToTensor(),
        transforms.Normalize([0.5], [0.5])
    ])
    tensor = transform(Image.fromarray(image)).unsqueeze(0).to(device)
    model.eval()
    with torch.no_grad():
        hash_out, _ = model(tensor, None)
        hash_sigmoid = torch.sigmoid(hash_out)
        hash_bin = (hash_sigmoid > 0.5).int().cpu().numpy().flatten()
    return hash_bin

def load_database(csv_path):
    df = pd.read_csv(csv_path)
    codes = df.iloc[:, 3:].values.astype(int)
    labels = df["person_id"].values
    image_names = df["image"].values
    return codes, labels, image_names

def hamming_distance(a, b):
    return np.sum(a != b)

def match_code(code, db_codes, db_labels, db_names, threshold):
    min_dist = HASH_BITS + 1
    best_idx = -1
    for i, entry in enumerate(db_codes):
        dist = hamming_distance(code, entry)
        if dist < min_dist:
            min_dist = dist
            best_idx = i
    matched = min_dist <= threshold
    return matched, min_dist, db_labels[best_idx], db_names[best_idx]

class IrisApp:
    def __init__(self, root):
        self.root = root
        self.root.title("Iris Recognition System - Enhanced")

        self.input_path = None
        self.mask = None
        self.overlay = None
        self.norm_img = None
        self.code = None
        self.original_size = (320, 240)

        self.setup_ui()

    def setup_ui(self):
        self.load_btn = tk.Button(self.root, text="Load Image", command=self.load_image)
        self.load_btn.grid(row=0, column=0, padx=5, pady=5)

        self.seg_btn = tk.Button(self.root, text="Segmentation", command=self.run_segmentation)
        self.seg_btn.grid(row=1, column=0, padx=5, pady=5)

        self.mask_btn = tk.Button(self.root, text="Show Mask", command=lambda: self.display_image(self.mask, 2))
        self.mask_btn.grid(row=2, column=0, padx=5, pady=5)

        self.overlay_btn = tk.Button(self.root, text="Show Overlay", command=lambda: self.display_image(self.overlay, 2))
        self.overlay_btn.grid(row=3, column=0, padx=5, pady=5)

        self.norm_btn = tk.Button(self.root, text="Normalization", command=self.run_normalization)
        self.norm_btn.grid(row=4, column=0, padx=5, pady=5)

        self.encode_btn = tk.Button(self.root, text="Feature Extraction", command=self.run_encoding)
        self.encode_btn.grid(row=5, column=0, padx=5, pady=5)

        self.match_btn = tk.Button(self.root, text="Matching", command=self.run_matching)
        self.match_btn.grid(row=6, column=0, padx=5, pady=5)

        self.canvas = tk.Label(self.root)
        self.canvas.grid(row=0, column=1, rowspan=8, padx=10, pady=10)

        self.output = tk.Text(self.root, height=10, width=80)
        self.output.grid(row=7, column=0, columnspan=2, padx=5, pady=10)

        self.hash_label = tk.Label(self.root, text="", wraplength=700, justify="left", font=("Courier", 8))
        self.hash_label.grid(row=8, column=0, columnspan=2, pady=5)

    def display_image(self, img, row):
        if img is None:
            messagebox.showinfo("Info", "Image not available.")
            return
        h, w = img.shape[:2]
        max_w = 320
        scale = max_w / w
        disp = cv2.resize(img, (int(w * scale), int(h * scale)), interpolation=cv2.INTER_AREA)
        disp = cv2.cvtColor(disp, cv2.COLOR_BGR2RGB) if len(disp.shape) == 3 else cv2.cvtColor(cv2.cvtColor(disp, cv2.COLOR_GRAY2BGR), cv2.COLOR_BGR2RGB)
        im = Image.fromarray(disp)
        photo = ImageTk.PhotoImage(im)
        self.canvas.configure(image=photo)
        self.canvas.image = photo

    def load_image(self):
        path = filedialog.askopenfilename(filetypes=[("Images", "*.jpg *.png *.bmp")])
        if not path:
            return
        self.input_path = path
        self.image_cv = cv2.imread(path)
        self.original_size = self.image_cv.shape[:2][::-1]
        self.display_image(self.image_cv, 2)
        self.output.delete("1.0", tk.END)
        self.output.insert(tk.END, f"Loaded: {os.path.basename(path)}\n")

    def run_segmentation(self):
        if not self.input_path:
            return
        device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
        model = UNet().to(device)
        model.load_state_dict(torch.load(SEG_MODEL_PATH, map_location=device))
        t0 = time.time()
        self.mask = segment_iris(self.input_path, model, device)
        t1 = time.time()
        ori_img = self.image_cv.copy()
        # contours, _ = cv2.findContours(self.mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
        # self.overlay = ori_img.copy()
        # cv2.drawContours(self.overlay, contours, -1, (0, 255, 0), 2)
        contours, _ = cv2.findContours(self.mask, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
        self.overlay = ori_img.copy()
        cv2.drawContours(self.overlay, contours, -1, (0, 255, 0), 2)
        self.output.insert(tk.END, f"Segmentation Done. Time: {t1 - t0:.2f}s\n")
        self.display_image(self.overlay, 2)

    def run_normalization(self):
        if self.mask is None:
            messagebox.showinfo("Info", "Please segment first.")
            return
        t0 = time.time()
        self.norm_img = normalize_and_crop(self.input_path, self.mask)
        t1 = time.time()
        self.output.insert(tk.END, f"Normalization Done. Time: {t1 - t0:.2f}s\n")
        self.display_image(self.norm_img, 2)

    def run_encoding(self):
        if self.norm_img is None:
            messagebox.showinfo("Info", "Please normalize first.")
            return
        device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
        model = ArcFaceIrisNet(num_classes=NUM_CLASSES, hash_bits=HASH_BITS).to(device)
        state_dict = torch.load(ENCODE_MODEL_PATH, map_location=device)
        model.load_state_dict({k: v for k, v in state_dict.items() if "classifier" not in k}, strict=False)
        t0 = time.time()
        self.code = encode_feature(self.norm_img, model, device)
        t1 = time.time()
        self.output.insert(tk.END, f"Encoding Done. Time: {t1 - t0:.2f}s\n")
        hash_string = ''.join(str(x) for x in self.code.tolist())
        self.hash_label.config(text=f"Feature Hash (256-bit):\n{hash_string}")

    def run_matching(self):
        if self.code is None:
            messagebox.showinfo("Info", "Please extract features first.")
            return
        db_codes, db_labels, db_names = load_database(ENCODE_DB_CSV)
        with open(THRESHOLD_TXT, "r") as f:
            best_threshold = int(f.readline().strip().split("=")[1])
        t0 = time.time()
        matched, dist, pred_id, pred_img = match_code(self.code, db_codes, db_labels, db_names, best_threshold)
        t1 = time.time()
        self.output.insert(tk.END, f"Predicted ID: {pred_id}\nHamming Distance: {dist} / {HASH_BITS}  (Threshold: {best_threshold})\nMatch: {'Accepted' if matched else 'Rejected'}\nMatching Time: {t1 - t0:.2f}s\n")

if __name__ == '__main__':
    root = tk.Tk()
    app = IrisApp(root)
    root.mainloop()