# Full iris recognition pipeline
# Workflow:
# 1. Segmentation
# 2. Normalization
# 3. Encoding
# 4. Matching

import os
import time
import torch
import numpy as np
import pandas as pd
import cv2
from PIL import Image
from tqdm import tqdm
from torchvision import transforms
from segmentation.seg_folder import UNet
from normalization.batch_normalization_half import normalize_iris_with_mask
from feature_extraction_encode.arcface_iris_model import ArcFaceIrisNet

# path to test image
IMG_PATH = r"C:\Users\User\Desktop\unsw\y2\9773\code\iris_ml\image.png"
# path to segmentation model unet_model.pth
SEG_MODEL_PATH = r"C:\Users\User\Desktop\unsw\y2\9773\code\iris_ml\segmentation_result\unet_model.pth"
# path to feature extraction model best_model.pt
ENCODE_MODEL_PATH = r"C:\Users\User\Desktop\unsw\y2\9773\code\iris_ml\feature_extraction_encoding_result\best_model.pt"
# path to saved encoding csv train_encodings.csv
ENCODE_DB_CSV = r"C:\Users\User\Desktop\unsw\y2\9773\code\iris_ml\feature_extraction_encoding_result\train_encodings.csv"
# path to threshold txt generated by train_arcface_v3 code
THRESHOLD_TXT = r"C:\Users\User\Desktop\unsw\y2\9773\code\iris_ml\feature_extraction_encoding_result\threshold.txt"
# path to predicted result
OUTPUT_DIR = "system_predicted_outputs"
IMG_SIZE = (32, 512)
HASH_BITS = 256
NUM_CLASSES = 395

os.makedirs(OUTPUT_DIR, exist_ok=True)


def segment_iris(image_path, seg_model, device):
    image = Image.open(image_path).convert("RGB")
    orig_size = image.size

    transform = transforms.Compose([
        transforms.Resize((256, 256)),
        transforms.ToTensor()
    ])
    input_tensor = transform(image).unsqueeze(0).to(device)

    seg_model.eval()
    with torch.no_grad():
        output = seg_model(input_tensor)

    mask = output.squeeze().cpu().numpy()
    mask = (mask > 0.5).astype(np.uint8) * 255
    mask = cv2.resize(mask, orig_size[::-1], interpolation=cv2.INTER_NEAREST)

    # Post-processing to match seg_folder.py
    kernel = np.ones((5, 5), np.uint8)
    mask = cv2.morphologyEx(mask, cv2.MORPH_CLOSE, kernel)
    mask = cv2.GaussianBlur(mask, (5, 5), 0)

    return mask


def normalize_and_crop(image_path, mask):
    # Step 2: Normalize and keep lower half of iris
    gray = cv2.imread(image_path, cv2.IMREAD_GRAYSCALE)
    norm = normalize_iris_with_mask(gray, mask)
    norm = norm[norm.shape[0] // 2:, :]
    return norm

def encode_feature(image, model, device):
    # Step 3: Extract binary hash feature from image
    transform = transforms.Compose([
        transforms.Resize(IMG_SIZE),
        transforms.ToTensor(),
        transforms.Normalize([0.5], [0.5])
    ])
    tensor = transform(Image.fromarray(image)).unsqueeze(0).to(device)
    model.eval()
    with torch.no_grad():
        hash_out, _ = model(tensor, None)
        hash_sigmoid = torch.sigmoid(hash_out)
        hash_bin = (hash_sigmoid > 0.5).int().cpu().numpy().flatten()
    return hash_bin

def load_database(csv_path):
    # Step 4: Load hash code database
    df = pd.read_csv(csv_path)
    codes = df.iloc[:, 3:].values.astype(int)
    labels = df["person_id"].values
    image_names = df["image"].values
    return codes, labels, image_names

def hamming_distance(a, b):
    return np.sum(a != b)

def match_code(code, db_codes, db_labels, db_names, threshold):
    # Match query code against database entries
    min_dist = HASH_BITS + 1
    best_idx = -1
    for i, entry in enumerate(db_codes):
        dist = hamming_distance(code, entry)
        if dist < min_dist:
            min_dist = dist
            best_idx = i
    matched = min_dist <= threshold
    return matched, min_dist, db_labels[best_idx], db_names[best_idx]

def main():
    # Main pipeline with progress and result logging
    start_all = time.time()
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

    with tqdm(total=5, bar_format="{l_bar}{bar}| {n_fmt}/{total_fmt} [{elapsed}<{remaining}]") as pbar:
        # Step 1: Segmentation
        t0 = time.time()
        tqdm.write("Load segmentation model and predict mask")
        seg_model = UNet().to(device)
        seg_model.load_state_dict(torch.load(SEG_MODEL_PATH, map_location=device))
        mask = segment_iris(IMG_PATH, seg_model, device)
        cv2.imwrite(os.path.join(OUTPUT_DIR, "seg_mask.png"), mask)
        ori_img = cv2.imread(IMG_PATH)
        contours, _ = cv2.findContours(mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
        overlay = ori_img.copy()
        cv2.drawContours(overlay, contours, -1, (0, 255, 0), 2)
        cv2.imwrite(os.path.join(OUTPUT_DIR, "seg_overlay.png"), overlay)
        tqdm.write(f"Segmentation: {time.time() - t0:.2f}s | Saved mask & overlay")
        pbar.update(1)

        # Step 2: Normalization
        t0 = time.time()
        tqdm.write("Normalize and crop lower iris")
        norm_img = normalize_and_crop(IMG_PATH, mask)
        cv2.imwrite(os.path.join(OUTPUT_DIR, "normalized_half.png"), norm_img)
        tqdm.write(f"Normalization: {time.time() - t0:.2f}s | Saved normalized image")
        pbar.update(1)

        # Step 3: Encoding
        t0 = time.time()
        tqdm.write("Load encoding model and generate hash")
        encode_model = ArcFaceIrisNet(num_classes=NUM_CLASSES, hash_bits=HASH_BITS).to(device)
        state_dict = torch.load(ENCODE_MODEL_PATH, map_location=device)
        filtered = {k: v for k, v in state_dict.items() if "classifier" not in k}
        encode_model.load_state_dict(filtered, strict=False)
        resized_img = cv2.resize(norm_img, IMG_SIZE[::-1])
        cv2.imwrite(os.path.join(OUTPUT_DIR, "encoded_input.png"), resized_img)
        code = encode_feature(norm_img, encode_model, device)
        tqdm.write(f"Encoding: {time.time() - t0:.2f}s | Saved encoded input")
        pbar.update(1)

        # Step 4: Matching
        t0 = time.time()
        tqdm.write("Load hash database and match")
        db_codes, db_labels, db_names = load_database(ENCODE_DB_CSV)
        with open(THRESHOLD_TXT, "r") as f:
            best_threshold = int(f.readline().strip().split("=")[1])
        matched, dist, pred_id, pred_img = match_code(code, db_codes, db_labels, db_names, 90)
        tqdm.write(f"⏱ Matching: {time.time() - t0:.2f}s")
        pbar.update(1)

        # Step 5: Result output
        tqdm.write("Output result")
        print("\n Match Result:")
        print(f"Predicted ID: {pred_id}")
        print(f"Matched Image: {pred_img}")
        print(f"Hamming Distance: {dist} / {HASH_BITS}  (Threshold: {best_threshold})")
        print(f"Match: {'Accepted' if matched else 'Rejected'}")
        print(f"Total time: {time.time() - start_all:.2f}s")
        pbar.update(1)

if __name__ == "__main__":
    main()
